"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

load_dotenv()
#Stripe
STRIPE_PUBLISHABLE_KEY = 'pk_test_51PjvhiGEkvCddTMkhHMT4uNQPMbbxSSZCX2cog0AgqEFN3V75yGstvBgiO59THwZqifQnZxhhhI4gDqQtHns4n5n00LV8g4A1k'
STRIPE_SECRET_KEY = 'sk_test_51PjvhiGEkvCddTMkI7McdSlvyjvBLRepuwJbtxXvyed473U7WQ9JWuUvEcQ1NNgJhIlxgWzLnKl6mkf8Exqeiys100zjMrprUJ'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mjpeg*@2(oj+^wvlc0&26x49kgpv+l)r*&ncg2d%!akve!%jbx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1)
}

INSTALLED_APPS = [
    'shopping.apps.ShoppingConfig', #added
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Added
    'rest_framework',
    'corsheaders',
]

FRONTEND_URL = 'http://localhost:5173'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bamazon_db',  # Replace with your database name
        'USER': 'bella',  # Replace with your PostgreSQL username
        'PASSWORD': 'sakowan21',  # Replace with your PostgreSQL password
        'HOST': 'localhost',  # Set to your PostgreSQL server address
        'PORT': '5432',  # Default port for PostgreSQL
    }
}

# Application definition
AUTH_USER_MODEL = 'shopping.BamUser'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = ['http://localhost:5173',
                        'http://127.0.0.1:5173',
                        ]
CSRF_TRUSTED_ORIGINS = ['http://localhost:5173',
                        'http://127.0.0.1:5173',
                        "http://localhost:8000",
                        "http://127.0.0.1:8000"
                        ]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
#     ]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
#     ]

HUBSPOT_API_KEY = "pat-na1-5f7ce832-8cf6-4d3e-a1fb-5ed5010587ec"
HUBSPOT_API_URL = 'https://api.hubapi.com'

TWILLIO_RECOVERY = "4RVUDAQM4P9WU8SMN2Y95ZKB"

#S3 BUCKET AMAZON KEYS
AWS_ACCESS_KEY_ID = 'AKIA3LET5YXPP35KUM5B'
AWS_SECRET_ACCESS_KEY = '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'

#EMAIL AMAZON KEYS ses-user raegalib; local code
# AWS_ACCESS_KEY_ID = 'AKIA3LET5YXPHF5HWV76'
# AWS_SECRET_ACCESS_KEY = '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'

AWS_STORAGE_BUCKET_NAME = 'orchid-app-bucket'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'ap-southeast-2'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_SES_REGION_NAME = 'ap-southeast-2'
AWS_SES_REGION_ENDPOINT = 'email.ap-southeast-2.amazonaws.com'
DEFAULT_FROM_EMAIL = 'orchidapp.team@gmail.com'