# Generated by Django 5.0.6 on 2024-07-22 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField()),
                ('type', models.CharField(choices=[(1, 'Percentage'), (2, 'Price Off')])),
                ('amount', models.PositiveIntegerField()),
                ('num_uses', models.PositiveIntegerField(default=1)),
                ('useby_datetime', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField()),
                ('prefecture', models.CharField()),
                ('city', models.CharField()),
                ('street', models.CharField()),
                ('building_name', models.CharField()),
                ('recipient_name', models.CharField()),
                ('recipient_phone', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BamUserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.coupon')),
            ],
            options={
                'unique_together': {('user', 'coupon')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Placed'), (2, 'Shipped'), (3, 'Out for delivery'), (4, 'Delivered'), (5, 'Cancelled')])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_coupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.bamusercoupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Order Missing'), (2, 'Incomplete Order'), (3, 'Damaged/Defective')])),
                ('resolved', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.order')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.productitem')),
            ],
            options={
                'unique_together': {('order', 'product_item')},
            },
        ),
    ]
