# Generated by Django 5.0.7 on 2024-08-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bamuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='bamuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
