# Generated by Django 5.0.7 on 2024-07-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_coupon_address_bamusercoupon_order_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Unspecified'), (1, 'Skincare'), (2, 'Makeup'), (3, 'Beauty Tools'), (4, 'Hair products')])),
            ],
        ),
        migrations.AddField(
            model_name='productlisting',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shopping.category'),
        ),
    ]
