# Generated by Django 5.0.7 on 2024-08-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_bamuser_username_alter_bamuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamuser',
            name='username',
            field=models.CharField(default='bella', unique=True, verbose_name=models.EmailField(max_length=254, unique=True)),
            preserve_default=False,
        ),
    ]
