# Generated by Django 5.0.7 on 2024-08-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_bamuser_username_alter_bamuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamuser',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True)),
        ),
    ]
