# Generated by Django 5.0.7 on 2024-08-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_bamuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bamuser',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), unique=True),
        ),
    ]
