# Generated by Django 5.0.7 on 2024-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_category_productlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
