# Generated by Django 5.0.7 on 2024-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_bamuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='url_name',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
