# Generated by Django 5.0.7 on 2024-08-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_productlisting_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='url_name',
            field=models.SlugField(blank=True, editable=False, max_length=150, unique=True),
        ),
    ]
