# Generated by Django 5.0.7 on 2024-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_productlisting_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlisting',
            old_name='description',
            new_name='desc_long',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='desc_brief',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
