# Generated by Django 5.0.7 on 2024-08-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_cartproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('product', 'cart')},
        ),
    ]
