# Generated by Django 5.0.7 on 2024-08-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_alter_cartproduct_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
