# Generated by Django 5.0.6 on 2024-09-18 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_orderproduct_delete_orderproductitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='type',
        ),
        migrations.AddField(
            model_name='complaint',
            name='info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Unassigned'), (2, 'In Progress'), (3, 'Resolved')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='shopping.order'),
        ),
    ]
