# Generated by Django 5.0.6 on 2024-09-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_remove_complaint_type_complaint_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flagImg',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
