# Generated by Django 5.0.6 on 2024-09-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_complaintimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unassigned'), (1, 'In Progress'), (2, 'Resolved')], default=0),
        ),
    ]
