# Generated by Django 5.0.6 on 2024-09-19 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0025_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='info',
        ),
        migrations.CreateModel(
            name='ComplaintOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, null=True)),
                ('body', models.CharField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.complaint')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.orderproduct')),
            ],
            options={
                'unique_together': {('complaint', 'order_product')},
            },
        ),
        migrations.CreateModel(
            name='ComplaintOPImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='default/')),
                ('complaint_order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_op_images', to='shopping.complaintorderproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ComplaintImage',
        ),
    ]
