# Generated by Django 5.0.6 on 2024-09-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_remove_complaint_info_complaintorderproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_id',
            new_name='id',
        ),
    ]
