# Generated by Django 5.0.6 on 2024-09-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0027_rename_complaint_id_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintopimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
