# Generated by Django 5.0.6 on 2024-09-20 06:40

import shopping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0028_alter_complaintopimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintopimage',
            name='image',
            field=models.ImageField(upload_to=shopping.helpers.complaint_img_upload_path),
        ),
    ]
