# Generated by Django 5.0.6 on 2024-09-21 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0029_alter_complaintopimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='shopping.order'),
        ),
    ]
