# Generated by Django 5.0.6 on 2024-09-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0031_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintorderproduct',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shopping.complaint'),
        ),
    ]
