# Generated by Django 5.1.1 on 2024-10-15 06:48

import shopping.helpers
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0033_alter_complaintorderproduct_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintopimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=shopping.helpers.complaint_img_upload_path),
        ),
    ]
